apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-online
  namespace: ${OPERATOR_NAMESPACE}
spec:
  channel: stable
  name: amq-online
  source: ${CATALOG_SOURCE}
  sourceNamespace: openshift-marketplace
  startingCSV: amq-online.${PRODUCT_VERSION}
  installPlanApproval: ${INSTALL_PLAN_APPROVAL}