kind: Deployment
apiVersion: apps/v1
metadata:
  name: enmasse-operator
  labels:
    app: enmasse
    name: enmasse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: enmasse-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: enmasse-operator
      annotations:
        enmasse.io/version: "${VERSION}"
        enmasse.io/revision: "${REVISION}"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.enmasse.io/operator-infra
                    operator: In
                    values:
                      - "true"
      serviceAccountName: enmasse-operator
      volumes:
        - name: ca-bundle
          configMap:
            name: ca-bundle
            optional: true
      containers:
      - name: controller
        image: ${CONTROLLER_MANAGER_IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        volumeMounts:
          - name: ca-bundle
            mountPath: /var/run/secrets/enmasse.io
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REVISION
          value: "${REVISION}"
        - name: VERSION
          value: "${VERSION}"
        - name: CONTROLLER_ENABLE_MESSAGING_INFRASTRUCTURE
          value: "false"
        - name: OPERATOR_NAME
          value: "enmasse-operator"
        - name: IMAGE_PULL_POLICY
          value: "${IMAGE_PULL_POLICY}"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        - name: CONTROLLER_ENABLE_UPGRADER
          value: "true"
        - name: CONTROLLER_ENABLE_AUTHENTICATION_SERVICE
          value: "true"
        - name: CONTROLLER_ENABLE_ADDRESS_SPACE_CONTROLLER
          value: "true"
        - name: CONTROLLER_ENABLE_MESSAGING_USER
          value: "true"
        - name: CONTROLLER_ENABLE_CA_BUNDLE
          value: "true"
        - name: RELATED_IMAGE_ADDRESS_SPACE_CONTROLLER
          value: ${ADDRESS_SPACE_CONTROLLER_IMAGE}
        - name: RELATED_IMAGE_CONTROLLER_MANAGER
          value: ${CONTROLLER_MANAGER_IMAGE}
        - name: RELATED_IMAGE_ROUTER
          value: ${ROUTER_IMAGE}
        - name: RELATED_IMAGE_STANDARD_CONTROLLER
          value: ${STANDARD_CONTROLLER_IMAGE}
        - name: RELATED_IMAGE_AGENT
          value: ${AGENT_IMAGE}
        - name: RELATED_IMAGE_BROKER
          value: ${BROKER_IMAGE}
        - name: RELATED_IMAGE_BROKER_PLUGIN
          value: ${BROKER_PLUGIN_IMAGE}
        - name: RELATED_IMAGE_TOPIC_FORWARDER
          value: ${TOPIC_FORWARDER_IMAGE}
        - name: RELATED_IMAGE_NONE_AUTHSERVICE
          value: ${NONE_AUTHSERVICE_IMAGE}
        - name: RELATED_IMAGE_KEYCLOAK
          value: ${KEYCLOAK_IMAGE}
        - name: RELATED_IMAGE_KEYCLOAK_PLUGIN
          value: ${KEYCLOAK_PLUGIN_IMAGE}
        - name: CONTROLLER_ENABLE_CONSOLE_SERVICE
          value: "true"
        - name: RELATED_IMAGE_CONSOLE_INIT
          value: "${CONSOLE_INIT_IMAGE}"
        - name: RELATED_IMAGE_CONSOLE_SERVER
          value: "${CONSOLE_SERVER_IMAGE}"
        - name: RELATED_IMAGE_CONSOLE_PROXY_OPENSHIFT
          value: "${CONSOLE_PROXY_OPENSHIFT_IMAGE}"
        - name: RELATED_IMAGE_CONSOLE_PROXY_OPENSHIFT3
          value: "${CONSOLE_PROXY_OPENSHIFT3_IMAGE}"
        - name: RELATED_IMAGE_CONSOLE_PROXY_KUBERNETES
          value: "${CONSOLE_PROXY_KUBERNETES_IMAGE}"
        - name: CONSOLE_LINK_SECTION_NAME
          value: "${CONSOLE_LINK_SECTION_NAME}"
        - name: CONSOLE_LINK_NAME
          value: "${CONSOLE_LINK_NAME}"
        - name: CONSOLE_LINK_IMAGE_URL
          value: "${CONSOLE_LINK_IMAGE_URL}"
        - name: ENABLE_MONITORING
          value: "true"
